version: '3.7'
services:

  tor-node:
    image: osminogin/tor-simple
    restart: always
    depends_on:
      - nginx

  nginx:
    image: nginx
    restart: always
    links:
      - drupal:drupalhost
    volumes:
      - /srv/drupal:/srv/www:ro
      - /srv/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  # TODO: Replace with simple echo server or use traefik instead nginx
  drupal:
    image: osminogin/php-fpm
    restart: always
    links:
      - mysql:mysqlhost
    volumes:
      - /srv/drupal:/srv/www

mysql:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: changeme
